ISSSTE.Tramites2016.QuejasMedicas/Controllers/Promovente/CatalogoController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using ISSSTE.Tramites2016.QuejasMedicas.Controllers.Base;
using ISSSTE.Tramites2016.QuejasMedicas.Domain.InformacionService;
using ISSSTE.Tramites2016.QuejasMedicas.Helpers;
using ISSSTE.Tramites2016.QuejasMedicas.Model.InformacionDTO;
using ISSSTE.Tramites2016.QuejasMedicas.Model.UtilDTO;
using System.Web;
using System.Linq;
using System;
using ISSSTE.Tramites2016.Common.Security.Core;
using ISSSTE.Tramites2016.Common.Security.Helpers;

namespace ISSSTE.Tramites2016.QuejasMedicas.Controllers.Promovente
{
    public class CatalogoController : BaseController
    {

        public ActionResult GetUADyCS(bool SinTodos = true)
        {
            var catalogoService = new CatalogoService();
            var combo = catalogoService.GetUadyCs(IdSesionTipoTramite);
            if (IdSesionTipoTramite == 0)
                SinTodos = false;
            var respuesta = Tag.GeneracionCuerpoSelect(SinTodos, combo);
            return Json(respuesta, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetUserUADyCS(bool SinTodos = false)
        {
            var delegationIds = GelDelegationIds();

            var catalogoService = new CatalogoService();
            var combo = catalogoService.GetUserUADyCS(delegationIds);

            var respuesta = Tag.GeneracionCuerpoSelect(false, combo);
            return Json(respuesta, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTramiteUnidadMedicaEspecial(CalendarioDTO CalendarioDto)
        {
            var catalogoService = new CatalogoService();
            var combo = catalogoService.GetTramiteUnidadMedicaEspecial(CalendarioDto);
            var respuesta = Tag.GeneracionCuerpoSelect(true, combo);
            return Json(respuesta, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetBusquedaHorarioUADyCS(int TramiteUnidadAtencionId)
        {
            var catalogoService = new CatalogoService();
            IdFechaLimite = catalogoService.GetBusquedaHorarioUadyCs(TramiteUnidadAtencionId);
            return Json(IdFechaLimite, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        ///     combo de unidades por tipo de trámite
        /// </summary>
        /// <param name="CalendarioDto"></param>
        /// <returns></returns>
        public JsonResult GetTramiteUnidadMedica(CalendarioDTO CalendarioDto)
       {
            var catalogoService = new CatalogoService();
            //CalendarioDto.CatTipoTramiteId = IdSesionTipoTramite;
            var combo = catalogoService.GetTramiteUnidadMedica(CalendarioDto);
            var respuesta = Tag.GeneracionCuerpoSelect(false, combo);
            return Json(respuesta, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        ///     búsqueda predictiva de unidades
        /// </summary>
        /// <param name="Concepto"></param>
        /// <returns></returns>
        public JsonResult GetBusqueda(string Concepto)
        {
            var catalogoService = new CatalogoService();
            var respuesta = catalogoService.GetBusqueda(Concepto, IdSesionTipoTramite);
            return Json(respuesta, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        ///     búsqueda de horarios por día
        /// </summary>
        /// <param name="Concepto"></param>
        /// <param name="TramiteUnidadAtencionId"></param>
        /// <returns></returns>
        public JsonResult GetBusquedaDia(string Concepto, int TramiteUnidadAtencionId)
        {
            var catalogoService = new CatalogoService();
            var respuesta = catalogoService.GetBusquedaDia(Concepto, TramiteUnidadAtencionId);
            return Json(respuesta, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetBusquedaTipoTramite(bool ConTodos=false)
        {
            var catalogoService = new CatalogoService();
            var respuesta = catalogoService.GetBusquedaTipoTramite();
            var cadena = SelectHtml(respuesta, ConTodos);
            return Json(cadena, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetBusquedaEstadoCita(bool ConTodos=false)
        {
            var catalogoService = new CatalogoService();
            var respuesta = catalogoService.GetBusquedaEstadoCita();
            var cadena = SelectHtml(respuesta, ConTodos);
            return Json(cadena, JsonRequestBehavior.AllowGet);
        }

        #region Métodos privados

        private string SelectHtml(IEnumerable<DuplaValoresDTO> Elementos, bool ConTodos=false)
        {
            var cadena = "";
            if (ConTodos)
            {
                cadena += "<option value='0'>Selecciona</option>";
            }
            foreach (var item in Elementos)
                cadena += "<option value='" + item.Id + "'>" + item.Valor + "</option>";
            return cadena;
        }


        private int[] GelDelegationIds()
        {
            var owinContext = Request.GetOwinContext();

            var user = owinContext.GetAuthenticatedUser();

            if (user == null) return new int[0];

            var delegations = user.GetPropertyValues(IsssteUserPropertyTypes.UADyCS);

            if (delegations == null) return new int[0];

            var delegationIds = (from d in delegations
                                 select Convert.ToInt32(d.Value)).ToArray();

            return delegationIds;
        }

        #endregion
    }
}

ISSSTE.Tramites2016.QuejasMedicas/Controllers/Promovente/PromoventeController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using ISSSTE.Tramites2016.QuejasMedicas.Controllers.Base;
using ISSSTE.Tramites2016.QuejasMedicas.Domain.CuentaService;
using ISSSTE.Tramites2016.QuejasMedicas.Domain.InformacionService;
using ISSSTE.Tramites2016.QuejasMedicas.Model.Enums;
using ISSSTE.Tramites2016.QuejasMedicas.Model.InformacionDTO;
using ISSSTE.Tramites2016.QuejasMedicas.Model.UtilDTO;
using ISSSTE.Tramites2016.QuejasMedicas.Helpers;
using ISSSTE.Tramites2016.QuejasMedicas.DAL.InformacionDAO;
using ISSSTE.Tramites2016.Common.Mail;

namespace ISSSTE.Tramites2016.QuejasMedicas.Controllers.Promovente
{
    public class PromoventeController : BaseController
    {
        private readonly IMailService _mailService;

        public PromoventeController(IMailService MailService)
        {
            _mailService = MailService;
        }

        /// <summary>
        ///     Página principal del Promovente
        /// </summary>
        /// <param name="CatTipoTramiteId"></param>
        /// <returns></returns>
        public ActionResult Index(int CatTipoTramiteId = 0)
        {
            var promoventeService = new PromoventeService();
            var existeTramite = new PromoventeService().SeEncuentraTramite(CatTipoTramiteId);

            if (!existeTramite)
                return View("Error");

            Session.RemoveAll();
            var lenguajeCiudadanoService = new LenguajeCiudadanoService();
            Enumeracion.MensajesServidor = lenguajeCiudadanoService.ConsultaLenguajeCiudadanoServer();

            var listaMensajesVista = lenguajeCiudadanoService.ConsultaLenguajeCiudadano();

            TempData["Sistema"] = promoventeService.ConceptoTipoTramite(CatTipoTramiteId);
            IdSesionTipoTramite = CatTipoTramiteId;

            return View(listaMensajesVista);
        }


        public ActionResult Informacion(int CatTipoTramiteId)
        {
            var promoventeService = new PromoventeService();

            var existeTramite = new PromoventeService().SeEncuentraTramite(CatTipoTramiteId);

            if (!existeTramite)
                return View("Error");

            var promoventeDto = promoventeService.ConsultaListado(CatTipoTramiteId, true);

            promoventeDto.DuplaValores = new DuplaValoresDTO
            {
                Valor = "Información general sobre este trámite"
                //Informacion = "Información general del trámite y los requisitos que se deben cumplir."
            };

            return PartialView(promoventeDto);
        }

        public ActionResult InformacionAdicional()
        {
            var promoventeService = new PromoventeService();
            var promoventeDto = promoventeService.ConsultaListado(IdSesionTipoTramite, false);

            promoventeDto.DuplaValores = new DuplaValoresDTO
            {
                Valor = "Más información sobre este trámite",
                Informacion = "Información adicional a este trámite."
            };

            return PartialView(promoventeDto);
        }


        /// <summary>
        ///     Calendario para agendar citas
        /// </summary>
        /// <param name="CalendarioDto"></param>
        /// <returns></returns>
        public ActionResult Calendario(CalendarioDTO CalendarioDto)
        {
            var catalogoService = new CatalogoService();
            CalendarioDto.CatTipoTramiteId = IdSesionTipoTramite;
            CalendarioDto.IdFechaLimite = IdFechaLimite;
            TempData["Fecha"] = CalendarioDto.MesAnio;
            var respuesta = catalogoService.GetBusquedaHorario(CalendarioDto);

            return PartialView(respuesta);
        }

        /// <summary>
        ///     Consulta de una cita
        /// </summary>
        /// <param name="CitaDto"></param>
        /// <returns></returns>
        public ActionResult VerSolicitud(CitaDTO CitaDto)
        {
            Enumeracion.MensajesServidor = new LenguajeCiudadanoService().ConsultaLenguajeCiudadanoServer();

            if (string.IsNullOrEmpty(CitaDto.RespuestaCaptcha))
                return Json(
                Enumeracion.EnumVarios.Prefijo +
                Enumeracion.MensajesServidor[Enumeracion.EnumConstErrores.ErrorCaptchaNoProporcionada],
                JsonRequestBehavior.AllowGet);

            bool esCaptchaValido = CaptchaService.ValidarCaptcha(CitaDto.RespuestaCaptcha);

            if (!esCaptchaValido)
                return Json(
                Enumeracion.EnumVarios.Prefijo +
                Enumeracion.MensajesServidor[Enumeracion.EnumConstErrores.ErrorCaptchaNoValido],
                JsonRequestBehavior.AllowGet);

            var citaService = new CitaService();
            CitaDto = citaService.GetCita(CitaDto);

            if (CitaDto == null)
            {
                return Json(
                    Enumeracion.EnumVarios.Prefijo +
                    Enumeracion.MensajesServidor[Enumeracion.EnumConstErrores.CitaNoEncontrada],
                    JsonRequestBehavior.AllowGet);
            }


            CitaDto.EsRepresentante = (CitaDto.Promovente.CURP != CitaDto.Paciente.CURP);
            CitaDto.ConFolio = true;
            return PartialView(CitaDto);
        }

        public ActionResult VerSolicitudCompleta(CitaDTO CitaDto)
        {
            var citaService = new CitaService();
            CitaDto = citaService.GetCita(CitaDto);

            if (CitaDto == null)
            {
                return Json(
                    Enumeracion.EnumVarios.Prefijo +
                    Enumeracion.MensajesServidor[Enumeracion.EnumConstErrores.CitaNoEncontrada],
                    JsonRequestBehavior.AllowGet);
            }


            CitaDto.EsRepresentante = (CitaDto.Promovente.CURP != CitaDto.Paciente.CURP);

            return PartialView(CitaDto);
        }




        public ActionResult Agenda()
        {
            return PartialView();
        }

        public ActionResult Horario()
        {
            return PartialView();
        }

        public ActionResult Confirmacion()
        {
            return PartialView();
        }

        public ActionResult Consulta()
        {
            var valor = new DuplaValoresDTO
            {
                Valor = "Consulta de tu cita"                
            };
            return PartialView(valor);
        }

        public ActionResult Cancelacion()
        {
            var valor = new DuplaValoresDTO
            {
                Valor = "Cancelación de tu cita",
                Id = Enumeracion.EnumVarios.ConEliminacion                
            };
            return PartialView("Consulta", valor);
        }

        /// <summary>
        ///     Solicitud con datos de vista
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult VerSolicitudVista(GeneralCitaDTO GeneralCitaDto)
        {
            //var generalCitaDto = Newtonsoft.Json.JsonConvert.DeserializeObject<GeneralCitaDTO>(Cadena);
            var citaDto = new CitaDTO();

            DebugLog("Entró a PromoventeController.VerSolicitudVista");
            try
            {
                citaDto = new CitaDTO
                {
                    Fecha = Convert.ToDateTime(GeneralCitaDto.FechaFinal),
                    HoraInicio = GeneralCitaDto.HorarioFinal,
                    Unidad_Atencion = GeneralCitaDto.Unidad_Atencion,
                    UnidadMedicaId = GeneralCitaDto.UnidadMedicaId,
                    Unidad_Medica = GeneralCitaDto.Unidad_Medica,
                    Promovente = GetPromoventeVista(GeneralCitaDto),
                    Paciente = GeneralCitaDto.EsRepresentante ? GetPacienteVista(GeneralCitaDto) : new PersonaDTO(),
                    EsRepresentante = GeneralCitaDto.EsRepresentante,
                    TramiteUnidadAtencionId= GeneralCitaDto.TramiteUnidadAtencionId,
                    DomicilioId = GeneralCitaDto.DomicilioId,
                    ConFolio = false
                };


                var citaService = new CitaService();
                citaService.GetDomicilio(0, citaDto);
            }
            catch (Exception ex)
            {
                EscribirLog(new ExceptionContext(ControllerContext, ex));
            }

            return PartialView("../Promovente/VerSolicitud", citaDto);
        }

        /// <summary>
        ///     Cancelación de una cita
        /// </summary>
        /// <param name="GeneralCitaDto"></param>
        /// <returns></returns>
        public async Task<ActionResult> CancelarCita(GeneralCitaDTO GeneralCitaDto)
        {
            var citaService = new CitaService();

            var citaDto = new CitaDTO {SolicitudId = GeneralCitaDto.SolicitudId};
            citaDto = citaService.GetCita(citaDto);

            if(!EsSolicitudCancelable(citaDto))
                return Json(
                    Enumeracion.EnumVarios.Prefijo +
                    Enumeracion.MensajesServidor[Enumeracion.EnumConstErrores.ErrorExpiracionTiempoCancelacion],
                    JsonRequestBehavior.AllowGet);

            var mensaje = citaService.CancelarCita(GeneralCitaDto);

            if (!string.IsNullOrEmpty(mensaje) && !mensaje.Contains(Enumeracion.EnumVarios.Prefijo))
            {

                await SendMail(Enumeracion.EnumConsCorreo.CuerpoCorreoCitaCancelada,
                    Enumeracion.EnumConsCorreo.TituloCorreoCitaCancelada,Enumeracion.EnumConsCorreo.NotaCitaCancelada, citaDto);
            } 

            return Json(mensaje, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        ///     Agendar una cita por horario
        /// </summary>
        /// <param name="GeneralCitaDto"></param>
        /// <returns></returns>
        public async Task<ActionResult> AgendarCita(GeneralCitaDTO GeneralCitaDto)
        {
            var numeroFolio = Enumeracion.EnumVarios.Prefijo + "Excepción general";

            try

ISSSTE.Tramites2016.QuejasMedicas/Views/Promovente/Header.cshtml
<ol class="breadcrumb">
    <li>
        <a id="navegacionSistema" href="https://www.gob.mx/" style='text-decoration: none;'>
            <span class="icon icon-home" aria-hidden="true" id="idHome"></span>
            <!--&nbsp;&nbsp;@TempData["Sistema"]-->
        </a>
    </li>
    <li>
        <a id="navegacionSeccionInicio" style='text-decoration:none;'>
            <span></span> Inicio
        </a>
    </li>
    <li>
        <a id="navegacionSeccion" style='text-decoration:none;'>
            <span></span>
        </a>
    </li>
</ol>


<div class="row bottom-buffer">
    <h1 class="col-md-8">@TempData["Sistema"]</h1>
</div>

<div class="row">
    <div class="col-md-12 btn-group text-center" style="width:100%">
        @Tag.InputBoton("AcercaTramite", "Inicio", 3, 3, "", "icon-infocircle", "", "", "EventMain")
        @Tag.InputBoton("AgendaCita", "Agendar cita", 3, 3, "", "icon-calendar", "", "", "EventMain")
        @Tag.InputBoton("VerSolicitud", "Consultar cita", 3, 3, "", "icon-search", "", "", "EventMain")
        @Tag.InputBoton("CancelaCita", "Cancelar cita", 3, 3, "", "glyphicon glyphicon-remove", "", "", "EventMain")
       @* @Tag.InputBoton("InformacionAdicional", "Más información", 3, 3, "", "icon-phone", "", "", "EventMain")*@
    </div>
</div>

<div class="row" id="SeccionTrabajoGeneral"></div>

ISSSTE.Tramites2016.QuejasMedicas/Views/Promovente/InfoGeneral.cshtml
<div id="SeccionPasos">
    <ul class="wizard-steps">
        <li id="Paso1">
            <h5>Paso 1</h5>
            <span>Información del promovente y/o paciente</span>
        </li>
        <li id="Paso2">
            <h5>Paso 2</h5>
            <span>Información de la cita</span>
        </li>
        <li id="Paso3">
            <h5>Paso 3</h5>
            <span>Confirmación de la cita</span>
        </li>
        <li id="ResultadoAgenda" style="width:15%">
            <i class="glyphicon glyphicon-ok-circle"></i>
        </li>
    </ul>
</div>

ISSSTE.Tramites2016.QuejasMedicas/Views/Promovente/PrivacidadInt1.cshtml
<div class="container">
	<div class="col-md-10 col-md-offset-1 clearfix vertical-buffer">



		<h2>
			AVISO DE PRIVACIDAD INTEGRAL PARA GENERAR UNA CITA EN LA QUE SE DEBERÁ EXHIBIR LA DOCUMENTACIÓN QUE SE REQUIERE AL PRESENTAR UNA QUEJA MÉDICA DEL ISSSTE
		</h2>
		<h3>
			¿Quiénes somos?
		</h3>
		<p>
			El Instituto de Seguridad y Servicios Sociales de los Trabajadores del Estado (ISSSTE), con domicilio en calle Jesus García Corona 140, Colonia Buenavista,  Delegación Cuauhtémoc, C.P. 06350, Ciudad De México, es el sujeto obligado y responsable del uso y protección de sus datos personales, los cuales serán protegidos conforme a lo dispuesto por la Ley General de Protección de Datos Personales en Posesión de Sujetos Obligados y demás normativa que resulte aplicable.
		</p>
		<h3>
			¿Para qué fines utilizaremos sus datos personales?
		</h3>
		<p>
			Los datos personales que recabamos de Usted, a través del portal Institucional dentro de www.gob.mx, cuyo administrador y responsable del tratamiento es la Unidad de Gobierno Digital de la Secretaría de la Función Pública, los utilizaremos con la finalidad de generar una cita en la que se deberá exhibir la documentación que se requiere al presentar una queja médica del ISSSTE.
		</p>
		<h3>
			¿Qué datos personales utilizaremos para estos fines?
		</h3>
		<p>
			Para llevar a cabo las finalidades descritas en el presente aviso de privacidad, utilizaremos los siguientes datos personales del promovente y paciente:

			<ul>
				<li>Nombre completo del promovente o paciente</li>
				<li>CURP</li>
				<li>Sexo</li>
				<li>Número Telefónico fijo</li>
				<li>Número Telefónico celular</li>
				<li>Correo Electrónico</li>
				<li>Edad</li>

			</ul>
			(En caso de que el promovente y paciente sean la misma persona, se utilizaran los mismos datos personales.)

		</p>
		<h3>
			Fundamento legal para llevar a cabo el tratamiento
		</h3>
		<p>
			El ISSSTE trata los datos personales antes señalados con fundamento en el artículo 2 fracciones I y XXXIII de la Ley General de Protección de Datos Personales en Posesión de Sujetos Obligados vigente.
		</p>
		<h3>
			¿Cómo puede acceder, rectificar o cancelar sus datos personales, u oponerse a su uso?
		</h3>
		<p>
			Usted tiene derecho a conocer qué datos personales tenemos de Usted, para qué los utilizamos y las condiciones del uso que les damos (Acceso).
		</p>
		<p>
			Asimismo, es su derecho solicitar la corrección de su información personal en caso de que esté desactualizada, sea inexacta o incompleta (Rectificación); que la eliminemos de nuestros registros o bases de datos cuando considere que la misma no está siendo utilizada adecuadamente (Cancelación); así como oponerse al uso de sus datos personales para fines específicos (Oposición). Estos derechos se conocen como derechos ARCO.
		</p>
		<p>
			La solicitud de derechos ARCO debe ser presentada a través de los medios o ventanillas de atención señaladas en este aviso privacidad y debe contener la siguiente información:

			<ol>
				<li>El nombre y domicilio del titular o cualquier otro medio para recibir la respuesta (si el titular omite la dirección o cualquier otro medio que haya elegido para contactarlo, se tendrá por no recibida la solicitud).</li>
				<li>Los documentos que acrediten la identidad o la personalidad de su representante.</li>
				<li>La descripción clara y precisa de los datos personales respecto de los cuales el titular busca ejercer alguno de los derechos.</li>
				<li>En su caso, otros elementos o documentos que faciliten la localización de los datos personales.</li>

			</ol>
		</p>
		<h3>
			Para el ejercicio de cualquiera de los derechos ARCO, usted deberá presentar la solicitud respectiva a través del siguiente medio:
		</h3>
		<p>
			Los datos de contacto de la persona o departamento de datos personales, que está a cargo de dar trámite a las solicitudes de derechos ARCO, son los siguientes:

			<ul class="list-unstyled">
				<li>	a)	Subdirección de Atención al Derechohabiente del ISSSTE; con domicilio en calle Jesus García Corona 140, piso 5 ala “A”, en la colonia Buenavista, Ciudad de México, delegación Cuauhtémoc, C.P. 06350, en la Ciudad De México.</li>
			</ul>
		</p>
		<h3>
			Usted puede revocar su consentimiento para el uso de sus datos personales o limitar el uso o divulgación de su información personal.

		</h3>
		<p>
			Usted puede revocar el consentimiento que, en su caso, nos haya otorgado para el tratamiento de sus datos personales. Sin embargo, es importante que tenga en cuenta que no en todos los casos podremos atender su solicitud o concluir el uso de forma inmediata, ya que es posible que por alguna obligación legal requiramos seguir tratando sus datos personales. Asimismo, usted deberá considerar que para ciertos fines, la revocación de su consentimiento implicará que no le podamos seguir prestando el servicio que nos solicitó, o la conclusión de su relación con nosotros.


		</p>
		<p>
			Para revocar su consentimiento  o limitar el uso o divulgación de su información personal deberá presentar su solicitud a la Subdirección de Atención al Derechohabiente del ISSSTE.
		</p>
		<h3>
			Transferencia de datos personales
		</h3>
		<p>
			No se realizarán transferencias de datos personales, salvo aquéllas que sean necesarias para atender requerimientos de información de una autoridad competente, que esté debidamente fundados y motivados.
		</p>
		<h3>
			¿Cómo puede conocer los cambios en este aviso de privacidad?
		</h3>
		<p>
			El presente aviso de privacidad puede sufrir modificaciones, cambios o actualizaciones derivadas de nuevos requerimientos legales; de nuestras propias necesidades por los productos o servicios que ofrecemos; de nuestras prácticas de privacidad; de cambios en nuestro modelo de negocio, o por otras causas.
		</p>
		<p>
			Nos comprometemos a mantenerlo informado sobre los cambios que pueda sufrir el presente aviso de privacidad, a través de la liga @Html.ActionLink("www.gob.mx/digitalizaciondecitas/privacidadintegral", "PrivacidadIntegral", "Promovente", new { CatTipoTramiteId = 1 }, null)

		</p>
	</div>
</div>

ISSSTE.Tramites2016.QuejasMedicas/Views/Promovente/PrivacidadMin1.cshtml
<div class="alert alert-info">
	<strong>AVISO DE PRIVACIDAD SIMPLIFICADO PARA GENERAR UNA CITA EN LA QUE SE DEBERÁ EXHIBIR LA DOCUMENTACIÓN QUE SE REQUIERE AL PRESENTAR UNA QUEJA MÉDICA DEL ISSSTE</strong>
	<p>
		El Instituto de Seguridad y Servicios Sociales de los Trabajadores del Estado, es el responsable del uso y protección de los datos personales que se recaban para generar la cita en la que se deberá exhibir la documentación que se requiere al presentar una queja médica del ISSSTE.
	</p>
	<p>
		Los datos personales que se recaban serán utilizados con la finalidad de generar una cita en la que se deberá exhibir la documentación que se requiere al presentar una queja médica del ISSSTE.
	</p>
	<p>

		Si deseas conocer nuestro aviso de privacidad integral, lo podrás consultar en el portal
		@Html.ActionLink("www.gob.mx/digitalizaciondecitas/privacidadintegral", "PrivacidadIntegral", "Promovente", new { CatTipoTramiteId = 1 }, new { target = "_blank" })
	</p>

</div>

ISSSTE.Tramites2016.QuejasMedicas/Views/Promovente/PrivacidadMin2.cshtml
<div class="alert alert-info">
	<strong>AVISO DE PRIVACIDAD SIMPLIFICADO PARA GENERAR UNA CITA EN LA QUE SE DEBERÁ EXHIBIR LA DOCUMENTACIÓN QUE SE REQUIERE AL PRESENTAR UNA SOLICITUD DE REEMBOLSO POR GASTOS MÉDICOS EXTRAINSTITUCIONALES DEL ISSSTE</strong>
	<p>
		El Instituto de Seguridad y Servicios Sociales de los Trabajadores del Estado, es el responsable del uso y protección de los datos personales que se recaban para generar la cita en la que se deberá exhibir la documentación que se requiere al presentar solicitud de reembolso por gastos médicos extrainstitucionales del ISSSTE.
	</p>
	<p>
		Los datos personales que se recaban serán utilizados con la finalidad de generar una cita en la que se deberá exhibir la documentación que se requiere al presentar solicitud de reembolso por gastos médicos extrainstitucionales del ISSSTE.
	</p>
	<p>
		Si deseas conocer nuestro aviso de privacidad integral, lo podrás consultar en el portal
		@Html.ActionLink("www.gob.mx/digitalizaciondecitas/privacidadintegral", "PrivacidadIntegral", "Promovente", new { CatTipoTramiteId = 2 }, new { target = "_blank" })

	</p>
</div>

ISSSTE.Tramites2016.QuejasMedicas/Views/Promovente/PrivacidadMin3.cshtml
<div class="alert alert-info">

	<strong>AVISO DE PRIVACIDAD SIMPLIFICADO PARA GENERAR UNA CITA EN LA QUE SE DEBERÁ EXHIBIR LA DOCUMENTACIÓN QUE SE REQUIERE AL PRESENTAR UNA SOLICITUD DE REEMBOLSO POR GASTOS MÉDICOS EXTRAINSTITUCIONALES DEL ISSSTE</strong>
	<p>
		El Instituto de Seguridad y Servicios Sociales de los Trabajadores del Estado, es el responsable del uso y protección de los datos personales que se recaban para generar la cita en la que se deberá exhibir la documentación que se requiere al presentar un recurso de reconsideración (derivado de las resoluciones de quejas médicas y/o solicitudes de reembolso) del ISSSTE.
	</p>
	<p>
		Los datos personales que se recaban serán utilizados con la finalidad de generar una cita en la que se deberá exhibir la documentación que se requiere al presentar un recurso de reconsideración (derivado de las resoluciones de quejas médicas y/o solicitudes de reembolso) del ISSSTE.
	</p>
	<p>
		Si deseas conocer nuestro aviso de privacidad integral, lo podrás consultar en el portal
		@Html.ActionLink("www.gob.mx/digitalizaciondecitas/privacidadintegral", "PrivacidadIntegral", "Promovente", new { CatTipoTramiteId = 3 }, new { target = "_blank" })


	</p>

</div>